from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle
)

from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from datetime import datetime


def generate_report(
        patient_file,
        prediction,
        probability,
        risk_level,
        biomarkers
):

    filename = "Parkinson_Clinical_Report.pdf"

    doc = SimpleDocTemplate(
        filename,
        pagesize=A4
    )


    styles = getSampleStyleSheet()

    content = []


    # Title

    content.append(
        Paragraph(
            "Parkinson AI Predictor",
            styles["Title"]
        )
    )

    content.append(
        Paragraph(
            "Clinical Decision Support Report",
            styles["Heading2"]
        )
    )


    content.append(
        Spacer(1,20)
    )


    # Patient + AI result

    data = [

        ["Patient File", patient_file],

        [
            "Analysis Date",
            str(datetime.now().date())
        ],

        [
            "Prediction",
            prediction
        ],

        [
            "Probability",
            f"{probability:.2f}%"
        ],

        [
            "Risk Level",
            risk_level
        ],

        [
            "AI Model",
            "Logistic Regression"
        ],

        [
            "Input Data",
            "RNA-Seq Gene Expression"
        ],

        [
            "Feature Set",
            "14 Biomarker Genes"
        ]

    ]


    table = Table(data)


    table.setStyle(
        TableStyle([

            (
                "GRID",
                (0,0),
                (-1,-1),
                0.5,
                colors.black
            ),

            (
                "BACKGROUND",
                (0,0),
                (0,-1),
                colors.lightgrey
            )

        ])
    )


    content.append(table)


    content.append(
        Spacer(1,25)
    )


    # Biomarkers

    content.append(
        Paragraph(
            "Selected Biomarkers",
            styles["Heading2"]
        )
    )


    for gene in biomarkers:

        content.append(
            Paragraph(
                "• " + gene,
                styles["Normal"]
            )
        )


    content.append(
        Spacer(1,25)
    )


    content.append(
        Paragraph(
            """
            Generated by Parkinson AI Predictor<br/>
            Biomedical Artificial Intelligence System<br/><br/>

            This software is developed for research and
            clinical decision-support purposes.
            """,
            styles["Normal"]
        )
    )


    doc.build(content)


    return filename