from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle
)

from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.pagesizes import letter
from datetime import datetime


def generate_report(
        filename,
        prediction,
        probability,
        risk,
        genes
):

    pdf_path = "Parkinson_Clinical_Report.pdf"

    doc = SimpleDocTemplate(
        pdf_path,
        pagesize=letter
    )


    styles = getSampleStyleSheet()

    story = []


    title = Paragraph(
        "Parkinson AI Predictor<br/>Clinical Analysis Report",
        styles["Title"]
    )

    story.append(title)

    story.append(
        Spacer(1,20)
    )


    info = [
        ["Patient File", filename],
        ["Analysis Date",
         str(datetime.now().date())],
        ["Prediction",
         prediction],
        ["Probability",
         f"{probability:.2f}%"],
        ["Risk Level",
         risk],
        ["Model",
         "Logistic Regression"],
        ["Feature Set",
         "14 Biomarker Genes"],
        ["Dataset",
         "RNA-Seq Gene Expression"]
    ]


    table = Table(info)

    table.setStyle(
        TableStyle([
            ("GRID",(0,0),(-1,-1),0.5,None)
        ])
    )


    story.append(table)

    story.append(
        Spacer(1,25)
    )


    story.append(
        Paragraph(
            "Selected Biomarkers",
            styles["Heading2"]
        )
    )


    for gene in genes:

        story.append(
            Paragraph(
                "• " + gene,
                styles["Normal"]
            )
        )


    story.append(
        Spacer(1,30)
    )


    story.append(
        Paragraph(
            "Generated by Parkinson AI Predictor<br/>"
            "Biomedical Artificial Intelligence System",
            styles["Normal"]
        )
    )


    doc.build(story)


    return pdf_path